import localFont from "next/font/local";
import "./globals.css";

const newRodin = localFont({
  src : [
    {
      path: "./fonts/NewRodin-Pro.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-newrodinpro",
  display: "swap",
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${newRodin.variable}`}>
        {children}
      </body>
    </html>
  );
}
